language: cpp
compiler:
  - gcc
  - clang
before_install:
  - git submodule update --init --recursive
  - sudo apt-get update
install:
  - sudo apt-get install libopencv-dev
script: make -C opencv2fx BITS=64
