language: cpp
compiler:
  - gcc
  - clang
before_install:
  - git submodule update --init --recursive
  - sudo apt-get update
install:
  - apt-get install libopencv-dev
script: make DEBUGFLAG=-O3 BITS=64
